# Fundamentos de Python con Numpy (Tarea Opcional)

Bienvenido a tu primera tarea. Este ejercicio te da una breve introducción a Python. Incluso si ya has usado Python antes, esto te ayudará a familiarizarte con las funciones que necesitaremos.

**Instrucciones:**
- Usarás Python 3.
- Evita usar bucles for y while, a menos que se te indique explícitamente que lo hagas.
- Después de programar tu función, ejecuta la celda justo debajo para verificar si tu resultado es correcto.

**Después de esta tarea podrás:**
- Usar iPython Notebooks
- Usar funciones de numpy y operaciones con matrices/vectores de numpy
- Entender el concepto de "broadcasting"
- Vectorizar código

¡Comencemos!

## Nota Importante sobre el Envío al AutoGrader

Antes de enviar tu tarea al AutoGrader, asegúrate de no estar haciendo lo siguiente:

1. No has añadido ninguna instrucción `print` _extra_ en la tarea.
2. No has añadido ninguna celda de código _extra_ en la tarea.
3. No has cambiado ninguno de los parámetros de las funciones.
4. No estás usando variables globales dentro de tus ejercicios calificados. A menos que se te indique específicamente, por favor abstente de hacerlo y usa variables locales en su lugar.
5. No estás cambiando el código de la tarea donde no es necesario, como crear variables _extra_.

Si haces cualquiera de lo anterior, obtendrás algo como `Grader Error: Grader feedback not found` (o un error inesperado similar) al enviar tu tarea. Antes de pedir ayuda/depurar los errores en tu tarea, verifica esto primero. Si este es el caso y no recuerdas los cambios que has hecho, puedes obtener una copia nueva de la tarea siguiendo estas [instrucciones](https://www.coursera.org/learn/neural-networks-deep-learning/supplement/iLwon/h-ow-to-refresh-your-workspace).

## Tabla de Contenidos
- [Acerca de los iPython Notebooks](#0)
    - [Ejercicio 1](#ex-1)
- [1 - Construyendo funciones básicas con numpy](#1)
    - [1.1 - Función sigmoide, np.exp()](#1-1)
        - [Ejercicio 2 - basic_sigmoid](#ex-2)
        - [Ejercicio 3 - sigmoid](#ex-3)
    - [1.2 - Gradiente de la Sigmoide](#1-2)
        - [Ejercicio 4 - sigmoid_derivative](#ex-4)
    - [1.3 - Redimensionando arreglos](#1-3)
        - [Ejercicio 5 - image2vector](#ex-5)
    - [1.4 - Normalizando filas](#1-4)
        - [Ejercicio 6 - normalize_rows](#ex-6)
        - [Ejercicio 7 - softmax](#ex-7)
- [2 - Vectorización](#2)
    - [2.1 Implementar las funciones de pérdida L1 y L2](#2-1)
        - [Ejercicio 8 - L1](#ex-8)
        - [Ejercicio 9 - L2](#ex-9)

<a name='0'></a>
## Acerca de los iPython Notebooks ##

Los iPython Notebooks son entornos de programación interactivos integrados en una página web. Usarás iPython notebooks en esta clase. Solo necesitas escribir código entre el comentario # your code here. Después de escribir tu código, puedes ejecutar la celda presionando "SHIFT"+"ENTER" o haciendo clic en "Run Cell" (representado por un símbolo de reproducción) en la barra superior del notebook.

A menudo especificaremos "(≈ X líneas de código)" en los comentarios para indicarte aproximadamente cuánto código necesitas escribir. Es solo una estimación aproximada, así que no te preocupes si tu código es más largo o más corto.

In [1]:
### v2.0

<a name='ex-1'></a>
### Ejercicio 1
Establece test como `"Hello World"` en la celda de abajo para imprimir "Hello World" y ejecuta las dos celdas siguientes.

In [1]:
# (≈ 1 line of code)
# test = 
# YOUR CODE STARTS HERE

test = "Hello World"

# YOUR CODE ENDS HERE

In [2]:
print ("test: " + test)

test: Hello World


**Resultado esperado**:
test: Hello World

<font color='blue'>
<b>Lo que necesitas recordar</b>:

- Ejecuta tus celdas usando SHIFT+ENTER (o "Run cell")
- Escribe código en las áreas designadas usando solo Python 3
- No modifiques el código fuera de las áreas designadas</font>

<a name='1'></a>
## 1 - Construyendo funciones básicas con numpy ##

Numpy es el paquete principal para computación científica en Python. Es mantenido por una gran comunidad (www.numpy.org). En este ejercicio aprenderás varias funciones clave de numpy como `np.exp`, `np.log` y `np.reshape`. Necesitarás saber cómo usar estas funciones para futuras tareas.

<a name='1-1'></a>
### 1.1 - Función sigmoide, np.exp() ###

Antes de usar `np.exp()`, usarás `math.exp()` para implementar la función sigmoide. Luego verás por qué `np.exp()` es preferible a `math.exp()`.

<a name='ex-2'></a>
### Ejercicio 2 - basic_sigmoid
Construye una función que devuelva la sigmoide de un número real x. Usa `math.exp(x)` para la función exponencial.

**Recordatorio**:
$sigmoid(x) = \frac{1}{1+e^{-x}}$ también se conoce a veces como la función logística. Es una función no lineal usada no solo en Machine Learning (Regresión Logística), sino también en Deep Learning.

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

Para referirse a una función que pertenece a un paquete específico, puedes llamarla usando `nombre_paquete.funcion()`. Ejecuta el código de abajo para ver un ejemplo con `math.exp()`.

In [28]:
import math
from public_tests import *

# GRADED FUNCTION: basic_sigmoid

def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    
    s = 1 / (1 + math.exp(-x))
    
    # YOUR CODE ENDS HERE
    
    return s

In [29]:
print("basic_sigmoid(x=1) = " + str(basic_sigmoid(1)))

basic_sigmoid_test(basic_sigmoid)

basic_sigmoid(x=1) = 0.7310585786300049
Test Case 1 (basic_sigmoid(x=1)):
 All tests passed.

Test Case 2 (basic_sigmoid(x=0.5)):
 All tests passed.


En realidad, rara vez usamos la biblioteca "math" en deep learning porque las entradas de las funciones son números reales. En deep learning principalmente usamos matrices y vectores. Por eso numpy es más útil.

In [ ]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###

x = [1, 2, 3] # x becomes a python list object
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

De hecho, si $ x = (x_1, x_2, ..., x_n)$ es un vector fila, entonces `np.exp(x)` aplicará la función exponencial a cada elemento de x. La salida será: `np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})`

In [ ]:
import numpy as np

# example of np.exp
t_x = np.array([1, 2, 3])
print(np.exp(t_x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Además, si x es un vector, entonces una operación de Python como $s = x + 3$ o $s = \frac{1}{x}$ producirá s como un vector del mismo tamaño que x.

In [ ]:
# example of vector operation
t_x = np.array([1, 2, 3])
print (t_x + 3)

[4 5 6]


Cada vez que necesites más información sobre una función de numpy, te animamos a consultar [la documentación oficial](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html).

También puedes crear una nueva celda en el notebook y escribir `np.exp?` (por ejemplo) para acceder rápidamente a la documentación.

<a name='ex-3'></a>
### Ejercicio 3 - sigmoid
Implementa la función sigmoide usando numpy.

**Instrucciones**: x ahora podría ser un número real, un vector o una matriz. Las estructuras de datos que usamos en numpy para representar estas formas (vectores, matrices...) se llaman arreglos de numpy. No necesitas saber más por ahora.
$$ \text{Para } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

In [ ]:
# GRADED FUNCTION: sigmoid

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    
    s = 1 / (1 + np.exp(-x))
    
    # YOUR CODE ENDS HERE
    
    return s

In [ ]:
t_x = np.array([1, 2, 3])
print("sigmoid(t_x) = " + str(sigmoid(t_x)))

sigmoid_test(sigmoid)

sigmoid(t_x) = [0.73105858 0.88079708 0.95257413]
All tests passed!


<a name='1-2'></a>
### 1.2 - Gradiente de la Sigmoide

Como has visto en la clase, necesitarás calcular gradientes para optimizar funciones de pérdida usando retropropagación (backpropagation). Vamos a programar tu primera función de gradiente.

<a name='ex-4'></a>
### Ejercicio 4 - sigmoid_derivative
Implementa la función sigmoid_grad() para calcular el gradiente de la función sigmoide con respecto a su entrada x. La fórmula es:

$$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

A menudo programarás esta función en dos pasos:
1. Establece s como la sigmoide de x. Puede que tu función sigmoid(x) te sea útil.
2. Calcula $\sigma'(x) = s(1-s)$

In [ ]:
# GRADED FUNCTION: sigmoid_derivative

def sigmoid_derivative(x):
    """
    Compute the gradient (also called the slope or derivative) of the sigmoid function with respect to its input x.
    You can store the output of the sigmoid function into variables and then use it to calculate the gradient.
    
    Arguments:
    x -- A scalar or numpy array

    Return:
    ds -- Your computed gradient.
    """
    
    #(≈ 2 lines of code)
    # s = 
    # ds = 
    # YOUR CODE STARTS HERE
    
    s = sigmoid(x)
    ds = s * (1 - s)
    
    # YOUR CODE ENDS HERE
    
    return ds

In [ ]:
t_x = np.array([1, 2, 3])
print ("sigmoid_derivative(t_x) = " + str(sigmoid_derivative(t_x)))

sigmoid_derivative_test(sigmoid_derivative)

sigmoid_derivative(t_x) = [0.19661193 0.10499359 0.04517666]
All tests passed!


<a name='1-3'></a>
### 1.3 - Redimensionando arreglos ###

Dos funciones comunes de numpy usadas en deep learning son [np.shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) y [np.reshape()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html).
- X.shape se usa para obtener la forma (dimensión) de una matriz/vector X.
- X.reshape(...) se usa para redimensionar X a alguna otra dimensión.

Por ejemplo, en ciencias de la computación, una imagen se representa como un arreglo 3D de forma $(largo, alto, profundidad = 3)$. Sin embargo, cuando lees una imagen como entrada de un algoritmo, la conviertes en un vector de forma $(largo*alto*3, 1)$. En otras palabras, "desenrollas" o redimensionas el arreglo 3D en un vector 1D.

<img src="images/image2vector_kiank.png" style="width:500px;height:300;">

<a name='ex-5'></a>

### Ejercicio 5 - image2vector
Implementa `image2vector()` que toma una entrada de forma (largo, alto, 3) y devuelve un vector de forma (largo\*alto\*3, 1). Por ejemplo, si quisieras redimensionar un arreglo v de forma (a, b, c) en un vector de forma (a*b, c) harías:
``` python
v = v.reshape((v.shape[0] * v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c
```
- Por favor no escribas las dimensiones de la imagen como constantes. En su lugar, busca las cantidades que necesitas con `image.shape[0]`, etc.
- Puedes usar v = v.reshape(-1, 1). Solo asegúrate de entender por qué funciona.

In [ ]:
# GRADED FUNCTION:image2vector

def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    # (≈ 1 line of code)
    # v =
    # YOUR CODE STARTS HERE
    
    v = image.reshape(-1, 1)
    
    # YOUR CODE ENDS HERE
    
    return v

In [ ]:
# This is a 3 by 3 by 2 array, typically images will be (num_px_x, num_px_y,3) where 3 represents the RGB values
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(t_image)))

image2vector_test(image2vector)


image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
All tests passed!


<a name='1-4'></a>
### 1.4 - Normalizando filas

Otra técnica común que usamos en Machine Learning y Deep Learning es normalizar nuestros datos. A menudo conduce a un mejor rendimiento porque el descenso de gradiente converge más rápido después de la normalización. Aquí, por normalización nos referimos a cambiar x a $ \frac{x}{\| x\|} $ (dividir cada vector fila de x por su norma).

Por ejemplo, si
$$x = \begin{bmatrix}
        0 & 3 & 4 \\
        2 & 6 & 4 \\
\end{bmatrix}\tag{3}$$
entonces
$$\| x\| = \text{np.linalg.norm(x, axis=1, keepdims=True)} = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{4} $$
y
$$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{5}$$

Nota que puedes dividir matrices de diferentes tamaños y funciona bien: esto se llama broadcasting y vas a aprender sobre ello en la parte 5.

Con `keepdims=True` el resultado se transmitirá correctamente contra la x original.

`axis=1` significa que vas a obtener la norma por filas. Si necesitas la norma por columnas, necesitarías establecer `axis=0`.

numpy.linalg.norm tiene otro parámetro `ord` donde especificamos el tipo de normalización a realizar (en el ejercicio de abajo harás la norma-2). Para familiarizarte con los tipos de normalización puedes visitar [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)

<a name='ex-6'></a>
### Ejercicio 6 - normalize_rows
Implementa normalizeRows() para normalizar las filas de una matriz. Después de aplicar esta función a una matriz de entrada x, cada fila de x debería ser un vector de longitud unitaria (es decir, longitud 1).

In [ ]:
# GRADED FUNCTION: normalize_rows

def normalize_rows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    
    #(≈ 2 lines of code)
    # Compute x_norm as the norm 2 of x. Use np.linalg.norm(..., ord = 2, axis = ..., keepdims = True)
    # x_norm =
    # Divide x by its norm.
    # x =
    # YOUR CODE STARTS HERE
    
    x_norm = np.linalg.norm(x, ord=2, axis=1, keepdims=True)
    x = x / x_norm
    
    # YOUR CODE ENDS HERE

    return x

In [ ]:
x = np.array([[0., 3., 4.],
              [1., 6., 4.]])
print("normalizeRows(x) = " + str(normalize_rows(x)))

normalizeRows_test(normalize_rows)

normalizeRows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]
All tests passed!


**Nota**:
En normalize_rows(), puedes intentar imprimir las formas de x_norm y x, y luego volver a ejecutar la evaluación. Descubrirás que tienen formas diferentes. Esto es normal dado que x_norm toma la norma de cada fila de x. Así que x_norm tiene el mismo número de filas pero solo 1 columna. Entonces, ¿cómo funcionó cuando dividiste x por x_norm? Esto se llama broadcasting y hablaremos de ello ahora.

<a name='ex-7'></a>
### Ejercicio 7 - softmax
Implementa una función softmax usando numpy. Puedes pensar en softmax como una función de normalización usada cuando tu algoritmo necesita clasificar dos o más clases. Aprenderás más sobre softmax en el segundo curso de esta especialización.

**Instrucciones**:
- $\text{para } x \in \mathbb{R}^{1\times n} \text{,     }$

\begin{align*}
 softmax(x) &= softmax\left(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}\right) \\&= \begin{bmatrix}
    \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} 
\end{align*}

- $\text{para una matriz } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ corresponde al elemento en la fila $i$ y columna $j$ de $x$, así tenemos: }$  

\begin{align*}
softmax(x) &= softmax\begin{bmatrix}
            x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
            x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
            \vdots & \vdots & \vdots & \ddots & \vdots \\
            x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
            \end{bmatrix} \\ \\&= 
 \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} \\ \\ &= \begin{pmatrix}
    softmax\text{(primera fila de x)}  \\
    softmax\text{(segunda fila de x)} \\
    \vdots  \\
    softmax\text{(última fila de x)} \\
\end{pmatrix} 
\end{align*}

**Notas:**
Nota que más adelante en el curso, verás "m" usado para representar el "número de ejemplos de entrenamiento", y cada ejemplo de entrenamiento está en su propia columna de la matriz. Además, cada característica estará en su propia fila (cada fila tiene datos para la misma característica).
Softmax debe realizarse para todas las características de cada ejemplo de entrenamiento, así que softmax se realizaría en las columnas (una vez que cambiemos a esa representación más adelante en este curso).

Sin embargo, en esta práctica de programación, solo nos estamos enfocando en familiarizarnos con Python, así que estamos usando la notación matemática común $m \times n$
donde $m$ es el número de filas y $n$ es el número de columnas.

In [ ]:
# GRADED FUNCTION: softmax

def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (m,n).

    Argument:
    x -- A numpy matrix of shape (m,n)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (m,n)
    """
    
    #(≈ 3 lines of code)
    # Apply exp() element-wise to x. Use np.exp(...).
    # x_exp = ...

    # Create a vector x_sum that sums each row of x_exp. Use np.sum(..., axis = 1, keepdims = True).
    # x_sum = ...
    
    # Compute softmax(x) by dividing x_exp by x_sum. It should automatically use numpy broadcasting.
    # s = ...
    
    # YOUR CODE STARTS HERE
    
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = x_exp / x_sum
    
    # YOUR CODE ENDS HERE
    
    return s

In [ ]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(t_x)))

softmax_test(softmax)

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]
All tests passed!


#### Notas
- Si imprimes las formas de x_exp, x_sum y s arriba y vuelves a ejecutar la celda de evaluación, verás que x_sum tiene forma (2,1) mientras que x_exp y s tienen forma (2,5). **x_exp/x_sum** funciona gracias al broadcasting de Python.

¡Felicidades! Ahora tienes una buena comprensión de Python numpy y has implementado algunas funciones útiles que usarás en deep learning.

<font color='blue'>
<b>Lo que necesitas recordar:</b>

- np.exp(x) funciona para cualquier np.array x y aplica la función exponencial a cada coordenada
- la función sigmoide y su gradiente
- image2vector se usa comúnmente en deep learning
- np.reshape se usa ampliamente. En el futuro, verás que mantener correctas las dimensiones de tus matrices/vectores te ayudará a eliminar muchos errores.
- numpy tiene funciones integradas eficientes
- el broadcasting es extremadamente útil</font>

<a name='2'></a>
## 2 - Vectorización

En deep learning, trabajas con conjuntos de datos muy grandes. Por lo tanto, una función que no sea computacionalmente óptima puede convertirse en un gran cuello de botella en tu algoritmo y puede resultar en un modelo que tarda mucho en ejecutarse. Para asegurarte de que tu código sea computacionalmente eficiente, usarás vectorización. Por ejemplo, intenta distinguir la diferencia entre las siguientes implementaciones del producto punto/exterior/elemento a elemento.

In [20]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0

for i in range(len(x1)):
    dot += x1[i] * x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1), len(x2))) # we create a len(x1)*len(x2) matrix with only zeros

for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i] * x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))

for i in range(len(x1)):
    mul[i] = x1[i] * x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])

for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j] * x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.1060000000000505ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

In [21]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(1000 * (toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.12400000000001299ms
outer = [[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
 ----- Computation time = 0.20300000000006424ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.0740000000000185ms
gdot = [27.76497554 18.96183405 19.7747346

Como habrás notado, la implementación vectorizada es mucho más limpia y eficiente. Para vectores/matrices más grandes, las diferencias en tiempo de ejecución se hacen aún mayores.

**Nota** que `np.dot()` realiza una multiplicación matriz-matriz o matriz-vector. Esto es diferente de `np.multiply()` y el operador `*` (que es equivalente a `.*` en Matlab/Octave), que realiza una multiplicación elemento a elemento.

<a name='2-1'></a>
### 2.1 Implementar las funciones de pérdida L1 y L2

<a name='ex-8'></a>
### Ejercicio 8 - L1
Implementa la versión vectorizada con numpy de la pérdida L1. Puede que encuentres útil la función abs(x) (valor absoluto de x).

**Recordatorio**:
- La pérdida se usa para evaluar el rendimiento de tu modelo. Cuanto mayor sea tu pérdida, más diferentes son tus predicciones ($ \hat{y} $) de los valores verdaderos ($y$). En deep learning, usas algoritmos de optimización como el Descenso de Gradiente para entrenar tu modelo y minimizar el costo.
- La pérdida L1 se define como:
$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^{m-1}|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [22]:
# GRADED FUNCTION: L1

def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    #(≈ 1 line of code)
    # loss = 
    # YOUR CODE STARTS HERE
    
    loss = np.sum(np.abs(yhat - y))
    
    # YOUR CODE ENDS HERE
    
    return loss

In [23]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat, y)))

L1_test(L1)

L1 = 1.1
All tests passed!


<a name='ex-9'></a>
### Ejercicio 9 - L2
Implementa la versión vectorizada con numpy de la pérdida L2. Hay varias formas de implementar la pérdida L2 pero puede que encuentres útil la función np.dot(). Como recordatorio, si $x = [x_1, x_2, ..., x_n]$, entonces `np.dot(x,x)` = $\sum_{j=1}^n x_j^{2}$.

- La pérdida L2 se define como 
$$L_2(\hat{y},y) = \sum_{i=0}^{m-1}(y^{(i)} - \hat{y}^{(i)})^2 \tag{7}$$

In [24]:
# GRADED FUNCTION: L2

def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    #(≈ 1 line of code)
    # loss = ...
    # YOUR CODE STARTS HERE
    
    loss = np.dot(yhat - y, yhat - y)
    
    # YOUR CODE ENDS HERE
    
    return loss

In [25]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print("L2 = " + str(L2(yhat, y)))

L2_test(L2)

L2 = 0.43
All tests passed!


¡Felicidades por completar esta tarea! Esperamos que este pequeño ejercicio de calentamiento te ayude en las futuras tareas, que serán más emocionantes e interesantes.

<font color='blue'>
<b>Lo que debes recordar:</b>

- La vectorización es muy importante en deep learning. Proporciona eficiencia computacional y claridad.
- Has revisado las pérdidas L1 y L2.
- Estás familiarizado con muchas funciones de numpy como np.sum, np.dot, np.multiply, np.maximum, etc...</font>